### ISSUE TITLE
CI: refactor how e2e tests are run in github actions

### ISSUE THREAD

**Issue by MSalopek** [cosmos/interchain-security#1175]
At present e2e tests are part of the `Automated tests` job which runs unit-, integration- and e2e-tests sequentially.

It would be beneficial to split e2e tests from unit- and integration-tests to simplify the the result reporting.

e2e happy path should run separately from other tests and have its own workflow file. The job's name should be `e2e-happy-path` and it should run on every push/commit.

Sources:
* https://github.com/cosmos/interchain-security/blob/main/.github/workflows/automated-tests.yml

------
Additionally, the [manual-e2e](https://github.com/cosmos/interchain-security/blob/main/.github/workflows/manual-e2e.yml) and [nightly-e2e](https://github.com/cosmos/interchain-security/blob/main/.github/workflows/nightly-e2e.yml) test runs should be refactored to include multiple tests runs instead of running all e2e test scenarios sequentially.

e.g. the jobs can be changed to include multiple job sections:

```
jobs:
  test-happy-path:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - uses: actions/checkout@v3
      - name: happy pathE2E tests
        run: make test-e2e-short
    multiconsumer-path:
      runs-on: ubuntu-latest
      timeout-minutes: 60
      steps:
        - uses: actions/setup-go@v4
          with:
            go-version: "1.20"
        - uses: actions/checkout@v3
        - name: happy pathE2E tests
          run: make test-e2e-multi-consumer
```

Most of the logic regarding the test starts existis in [main.go](https://github.com/cosmos/interchain-security/blob/main/tests/e2e/main.go) which the [Makefile](https://github.com/cosmos/interchain-security/blob/main/Makefile) uses to start the tests. The `Makefile` and `main.go` flags may need to be extended to support running the distinct paths individually.

-----------
**Note:**

Check the comments in https://github.com/cosmos/interchain-security/pull/1179 and consider splitting happy path into 2 smaller jobs - one with normal downtime and the other with soft opt-out/throttling downtime. That will require changes in the testing suite.
